services:
  front:
    image: ${IMAGEN_FRONT}
    restart: always
    ports:
      - "${PORT_FRONT}:443"
      - "${PORT_FRONT_ALTERNATIVO}:80"
    environment:
      - API_BASE_URL=http://backend/api
      - DATASCOPE_URL=${DATASCOPE_URL}
    env_file:
      - .env
    networks:
      - crm
    depends_on:
      - backend
  backend:
    image: ${IMAGEN_BACKEND}
    restart: always
    ports:
      - "${PORT_BACKEND}:443"
      - "${PORT_BACKEND_ALTERNATIVO}:80"
    env_file:
      - .env
    networks:
      - crm

networks:
  crm:
    driver: bridge